### ISSUE TITLE
8.x is active now, what is the LTS end date

### ISSUE THREAD

**Issue by AjayChoudary** [nodejs/Release#275] opened 2017-11-01 06:57 UTC
The 8.x Maintenance LTS cycle is currently scheduled to expire early on December 31, 2019 to align with the scheduled End-of-Life of OpenSSL-1.0.2. Note that this schedule may change if the version of OpenSSL is upgraded to 1.1.x before 8.x enters the Active LTS cycle.

Can we start using 8.x for production deployments?

**Comment by fivdi** [comment] 2017-11-01 07:15
> Can we start using 8.x for production deployments?

According to https://nodejs.org/en/ 8.9.0 LTS is recommended for most users.

**Comment by AjayChoudary** [comment] 2017-11-01 07:28
what is the LTS end date for 8.x ?

**Comment by fivdi** [comment] 2017-11-01 07:51
If my interpretation of the [release schedule](https://github.com/nodejs/Release#release-schedule) is correct the LTS plan for 8.x started yesterday and will end in April 2019.

That being said, the [image](https://github.com/nodejs/Release/blob/master/schedule.png) showing the release schedule doesn't appear to be consistent with the text describing the release plan. In the image the LTS plan appears to be for twelve rather than eighteen months.

I think the image should be updated to avoid confusion.

**Comment by cjihrig** [comment] 2017-11-01 13:25
> Can we start using 8.x for production deployments?

Node 8 entered LTS yesterday. It should be considered safe to use in production until December 2019.

> what is the LTS end date for 8.x ?

It will be active LTS until April 2019. Then it will become a maintenance LTS (still safe to use) until it is end of lifed in December 2019.

> I think the image should be updated to avoid confusion.

That image is pretty old, and I think the issue is that Node 8 runs off the side of the image. I generated this image, which is more up to date: https://gist.githubusercontent.com/cjihrig/a6fa74be5d9d99338390fe7f0d954aa5/raw/3e3fa423b15094a0bfebbd5038be6cbc34127bb5/lts.png

**Comment by fivdi** [comment] 2017-11-01 13:56
@cjihrig The updated image is a better reflection or reality today. Would it be even better if the time axis was extended for a further six months went up to Apr 2020? The axis would then include Jan 2020 and Apr 2020. The maintenance phase for Node 8 would go up as far as Jan 2020. It would then be clearer that the maintenance phase for Node 8 is nine months rather than twelve months. As it is now the maintenance phase for Node 8 looks like it's seven months long.

**Comment by MylesBorins** [comment] 2017-11-01 13:58
@rvagg I believe the graphic is created by node source. are you able to provide an update?

**Comment by cjihrig** [comment] 2017-11-01 14:03
@MylesBorins I'd like to suggest using https://www.npmjs.com/package/lts. I'm biased because I created it, but anyone can use it to autogenerate the graph for any time period, and it doesn't carry any company names.

**Comment by MylesBorins** [comment] 2017-11-01 14:23
Oh wow... I don't know why I thought it was an internal thing. A++ to no
company names

**Comment by gibfahn** [comment] 2017-11-01 16:11
@cjihrig could you PR an update to the README that uses `lts`?

Also https://www.npmjs.com/package/lts sounds like another candidate for @nodejs/automation

**Comment by cjihrig** [comment] 2017-11-01 16:27
@gibfahn https://github.com/nodejs/Release/pull/277

**Comment by joyeecheung** [comment] 2017-11-01 16:48
@cjihrig @gibfahn Yes it's mentioned in https://github.com/nodejs/automation/issues/1 ...should we open an issue somewhere (TSC or admin) to see if there are any objections on moving it into the foundation?

**Comment by gibfahn** [comment] 2017-11-01 21:39
>should we open an issue somewhere (TSC or admin) to see if there are any objections on moving it into the foundation? 

I think that should be the TSC repo.

>(Assuming the owners are willing to transfer it)

Owner is @cjihrig 😁

**Comment by cjihrig** [comment] 2017-11-01 21:40
As long as it's going to be used, I'm happy to transfer it.

**Comment by joyeecheung** [comment] 2017-11-02 04:32
@cjihrig OK, we can open an issue in the TSC repo once #277 lands

**Comment by MylesBorins** [comment] 2017-11-03 17:59
I've landed #277 

Feel free to open the issue

**Comment by mhdawson** [comment] 2017-11-20 14:06
Can we close this now ? Looks like the update to the image landed.

**Closed** 2017-11-20 14:30 UTC
