### ISSUE TITLE
Conflicting Youtube Stream?

### ISSUE THREAD

**Issue by jonchurch** [nodejs/Release#566] opened 2020-04-10 17:37 UTC
Hey there, over at https://github.com/expressjs/discussions/issues/115#issuecomment-612132143 I noticed something weird during our (Express') last meeting. When we tried to go live on youtube, Zoom pointed us to an already finished livestream of yours from 2 weeks ago. I'm assuming it also updated the title to what it is now "Express TSC Meeting" https://www.youtube.com/watch?v=kE1mY_k5oW4

Opened this to bring it to y'alls attention, I don't know what steps towards fixing this would be. I think @wesleytodd might know more.

**Comment by BethGriggs** [comment] 2020-04-10 17:53
👋 @jonchurch thanks . I think the issue is widespread and impacting all of our Node.js Zoom account streams and recordings. I think I remember hearing that @mhdawson had/has a ticket open to try and address the problem?

Either way - I will leave this issue open as an action/reminder to go through and manually correct the titles on the release videos.

**Comment by BridgeAR** [comment] 2020-05-21 14:35
@BethGriggs should this stay open?

**Comment by BethGriggs** [comment] 2020-05-21 22:26
If I recall, the problem was fixed by @mhdawson making the specific release livestream video private. I just manually uploaded the video - https://youtu.be/u8wydgW90QY.

So this can be closed I think.

**Closed by BethGriggs** 2020-05-21 22:26 UTC
