### ISSUE TITLE
Node.js release notify

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/Release#422] opened 2019-03-17 14:48 UTC
As Node.js grows quickly, there are many docker image add it to deps or 
use it as a base image. Like https://hub.docker.com/r/vuejs/ci and https://hub.docker.com/r/reactnativecommunity/react-native-android.

The main concern is that keep the docker image that including Node.js
can get release update after it's released. So users can trigger new image build or test automatically instead of read release update from twitter or news, then update the docker image to get security update or performance boost.

The implementation maybe using webhook or websocket ?

The other thing is that I don't know whether or not Node.js download count including docker pull(https://www.youtube.com/watch?v=BlFOGALPabY). If not but we should include it. From my experience, it's quite normal deploying Node.js services through docker.
cc @rvagg

**Comment by richardlau** [comment] 2019-03-17 15:11
Duplicate of https://github.com/nodejs/Release/issues/295?

**Comment by richardlau** [comment] 2019-03-17 15:12
FWIW there's GitHub's atom feed for releases:

![image](https://user-images.githubusercontent.com/5445507/54493360-0587fa00-48c7-11e9-9c5d-a2b809c31912.png)

**Comment by BridgeAR** [comment] 2019-04-29 15:50
Since we have the atom feed, I'm not sure there's really anything actionable left here?

**Closed** 2019-04-29 16:06 UTC

**Comment by BridgeAR** [comment] 2019-04-29 16:07
This also seems somewhat related to https://github.com/nodejs/Release/issues/322

**Comment by gengjiawen** [comment] 2019-04-29 16:30
Is atom feed can push notification ?

**Comment by targos** [comment] 2019-04-29 17:07
Note that it is now possible to subscribe to "Release only" notifications on GitHub.

![image](https://user-images.githubusercontent.com/2352663/56913423-f0031400-6ab1-11e9-8d37-a8760c655532.png)

**Comment by BridgeAR** [comment] 2019-04-29 17:22
@gengjiawen it has no push notifications

**Comment by TomasHubelbauer** [comment] 2019-04-29 18:15
@targos This repository has no releases. Did you mean a different repository?

**Comment by targos** [comment] 2019-04-29 18:18
I think we're talking about `nodejs/node`

**Comment by gengjiawen** [comment] 2019-05-01 05:05
The ideally way should github provide a subscription in their graphql api.
