### ISSUE TITLE
windows 10, nodejs 10.12.0 boxstarter dependency force reboot

### ISSUE THREAD

**Issue by rammadogs** [nodejs/Release#394] opened 2018-11-26 11:38 UTC
This issue seems to already exist but has been closed without being solved so I'm reposting it. You may argue that there was a warning but to see it, I would have had to read a huge wall of text. I understand the reason to restart the computer while installing something but there is no need to do so instantly with no warning and giving the user no chance to save their work. I just lost a heck of a lot of work that I'll never get back and I'm livid. This issue needs to be fixed NOW. It is never acceptable to forcefully close all applications and shut a computer down without warning. Whoever programmed this should be ashamed of themselves. Isn't it sufficient for the installation to pause while I save my work and restart manually? What about a very obvious popup box warning me of the restarts before installation starts? There are endless possibilities other than killing everything I'm working on. I will never use node.js again if this is the respect you're going to show to me and my work.

**Comment by richardlau** [comment] 2018-11-26 12:35
Duplicate of https://github.com/nodejs/Release/issues/369.

**Closed by richardlau** 2018-11-26 12:35 UTC
Labels: duplicate
