### ISSUE TITLE
Backporting exitedAfterDisconnect to v4.x

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/Release#232] opened 2017-06-15 14:43 UTC
Moving LTS conversation from https://github.com/nodejs/node/pull/7998

TLDR; Should it be backported? Should we do a minor in Maintenance mode?

**Comment by sam-github** [comment] 2017-06-15 14:57
I'm 50/50 on this. It is semver-minor, but its a minor that was intended to have already been released in 4.x, so the fact that it isn't there is a bug (not a semver-bug in node, but a bug in our release process).

We could not do it and see if anyone outside core notices or requests this. Issac won't, and I don't think he is maintaining https://github.com/isaacs/cluster-master/blob/master/cluster-master.js#L276 anymore, and I can do what has to be done in my own cluster-using code.

citgm was reported to not see issues, but I don't think cluster managers are the kinds of things that are in citgm.

**Comment by bnoordhuis** [comment] 2017-06-15 15:08
I've laid out my arguments in https://github.com/nodejs/node/pull/7998#issuecomment-308694405 and https://github.com/nodejs/node/pull/7998#issuecomment-308701002.

Short version: no.

**Closed** 2017-09-28 07:29 UTC
